[project]
name = "mathex"
version = "0.1.0"
description = "Simple parser and evaluator for Latex mathemaatical expressions."
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[dependency-groups]
dev = [
    "numpy>=2.3.5",
    "pytest>=9.0.1",
]
