[project]
name = "mathex"
version = "0.2.0a1"
description = "Simple parser and evaluator for Latex mathemaatical expressions."
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[dependency-groups]
dev = [
    "numpy>=2.2.6",
    "pytest>=9.0.1",
]
